### ISSUE TITLE
Bug #16 / Wrong text in pop-up window after clicking "Create account" in registration form

### ISSUE THREAD

**Issue by SofyaKovalenko** [spellsofenglish/frontend#18]
**Environment**	
Windows 10, Google Chrome, version 109.0.5414.120, ASUS 1366 x 768

**Build version**	
v0.0.1

**Module**
Sign up (FrontEnd)

**Severity**
Minor

**Priority**
Low

**Description**
Wrong text in pop-up window after clicking "Create account" in registration form

**Steps to reproduce**
1. Open link https://spells.hedgi.ru/
2. Click "Create account"
3. Fill in fields "Name", "Email", "Password", "Repeat password" with valid data
4. Click "Create account"

**Expected result**
1. Link is opened
2. Registration form is opened
3. Fields "Name", "Email", "Password", "Repeat password" are filled in
4. Pop-up window with text "We have sent you the link to [e-mail]. Please open it to finish your registration" is opened (Мы отправили ссылку на вашу почту. Пожалуйста, пройдите по ней, чтобы завершить регистрацию.)
	
**Actual result**
1. Link is opened
2. Registration form is opened
3. Fields "Name", "Email", "Password", "Repeat password" are filled in
4. Pop-up window with text "We sent a link to reset your password to [e-mail].
Follow the instructions of the letter and you will quickly return to the game!" is opened (Мы отправили ссылку **### на восстановление пароля** на [почта]. Cледуй инструкциям письма и ты быстро вернешься в игру!)

![bug 16 wrong text after registration](https://user-images.githubusercontent.com/129843527/232823870-283bfaee-d1dc-4930-a898-e806fcdf3995.png)

**Comment by zatrimaylova** [comment]
готово!

**Comment by SofyaKovalenko** [comment]
Re-test OK
