### ISSUE TITLE
Bug #24 / The text runs over the "Show / hide password" button if enter too long text in the password input field in sign up and click "Show password" (for log in form the same)

### ISSUE THREAD

**Issue by SofyaKovalenko** [spellsofenglish/frontend#28]
**Environment**	
Windows 10, Google Chrome, version 109.0.5414.120

**Build version**	
v0.0.1

**Module**
Sign up

**Description**
The text runs over the "Show / hide password" button if enter too long text in the password input field in sign up and click "Show password" (for log in form the same)

**Steps to reproduce**
1. Open link https://spells.hedgi.ru/
2. Click "Sign up"
3. Fill in field "Password" with 55 and more symbols
4. Click the button "Show password"

**Expected result**
The text does not run over the button "Show/hide password"
	
**Actual result**
The text runs over the button "Show/hide password"

![bug 24 show hide password](https://user-images.githubusercontent.com/129843527/233150003-707c456b-b771-4b7d-a6a8-b9db12fdbce1.png)

**Comment by PavelPashyk** [comment]
Fixed bug #24

**Comment by SofyaKovalenko** [comment]
Re-test OK
