### ISSUE TITLE
Bug #11 / Mistake "Passwords don't match each other" aren't shown in registration form when changing field "Password" after filling field "Repeat password"

### ISSUE THREAD

**Issue by SofyaKovalenko** [spellsofenglish/frontend#5]
**Environment**	
Windows 10, Google Chrome, version 109.0.5414.120, ASUS 1366 x 768

**Build version**	
v0.0.1

**Module**
Sign up (FrontEnd)	

**Severity**
Critical	

**Priority**
High	

**Description**
Mistake "Passwords don't match each other" aren't shown in registration form when changing field "Password" after filling field "Repeat password"	

**Steps to reproduce**
1. Open link https://spells.hedgi.ru/
2. Click "Create account"
3. Fill in field "Password" with "12345678"
4. Fill in field "Repeat password" with the same data from step No.3
5. Return to field "Password" and change it from "12345678" to "12345679" without changing field "Repeat password"	

**Expected result**
1. Link is opened
2. Registration form is opened
3. Field "Password" is filled in
4. Field "Repeat password" is filled in
5. Mistake "Passwords don't match each other"" is shown under the field ""Repeat password"
	
**Actual result**
1. Link is opened
2. Registration form is opened
3. Field "Password" is filled in
4. Field "Repeat password" is filled in
5. Mistake "Passwords don't match each other" is NOT shown under the field "Repeat password"

![bug repeat password](https://user-images.githubusercontent.com/129843527/230120070-dcc905d6-bead-412c-ac52-c73ac2335d6b.png)

**Comment by PavelPashyk** [comment]
Fixed bug #11

**Comment by SofyaKovalenko** [comment]
Re-test OK
