### ISSUE TITLE
Bug #12 / Button "Create account" is active when entering in field "Password" more than 24 symbols

### ISSUE THREAD

**Issue by SofyaKovalenko** [spellsofenglish/frontend#6]
**Environment**	
Windows 10, Google Chrome, version 109.0.5414.120, ASUS 1366 x 768

**Build version**	
v0.0.1

**Module**
Sign up (FrontEnd)

**Severity**
Major

**Priority**
Medium

**Description**
Button "Create account" is active when entering in field "Password" more than 24 symbols

**Steps to reproduce**
1. Open link https://spells.hedgi.ru/
2. Click "Create account"
3. Fill in fields "Name", "Email" with valid data
4. Fill in field "Password" with 30 symbols
5. Fill in field "Repeat password" with the same data from step No.3
6. Click the button "Create account"

**Expected result**
1. Link is opened
2. Registration form is opened
3. Fields "Name", "Email" are filled in
4. Field "Password" is filled in
5. Field "Repeat password" is filled in
6. The button "Create account" is not active
	
**Actual result**
1. Link is opened
2. Registration form is opened
3. Fields "Name", "Email" are filled in
4. Field "Password" is filled in
5. Field "Repeat password" is filled in
6. The button "Create account" is active

![bug password more 24symb ](https://user-images.githubusercontent.com/129843527/230138838-eb48ceba-ef7e-4081-8679-ef279c95030a.png)

**Comment by PavelPashyk** [comment]
Fixed bug №12

**Comment by SofyaKovalenko** [comment]
Re-test OK
