### ISSUE TITLE
Bug #13 / Mistake "Password must contain from 8 to 24 symbols" is not shown under the field "Password" when entering more then 24 symbols

### ISSUE THREAD

**Issue by SofyaKovalenko** [spellsofenglish/frontend#7]
**Environment**	
Windows 10, Google Chrome, version 109.0.5414.120, ASUS 1366 x 768

**Build version**	
v0.0.1

**Module**
Sign up (FrontEnd)

**Severity**
Minor

**Priority**
Low

**Description**
Mistake "Password must contain from 8 to 24 symbols" is not shown under the field "Password" when entering more then 24 symbols

**Steps to reproduce**
1. Open link https://spells.hedgi.ru/
2. Click "Create account"
3. Fill in fields "Name", "Email" with valid data
4. Fill in field "Password" with 30 symbols

**Expected result**
1. Link is opened
2. Registration form is opened
3. Fields "Name", "Email" are filled in
4. Mistake "Password must contain from 8 to 24 symbols" is shown under the field "Password"
	
**Actual result**
1. Link is opened
2. Registration form is opened
3. Fields "Name", "Email" are filled in
4. Mistake "Password must contain from 8 to 24 symbols" is NOT shown under the field "Password"

![bug password more 24symb mistake ](https://user-images.githubusercontent.com/129843527/230139783-018fa9b7-d479-4d8b-b270-fd4384f83b34.png)

**Comment by PavelPashyk** [comment]
Fixed bug №13

**Comment by SofyaKovalenko** [comment]
Re-test OK
