### ISSUE TITLE
Bug #14 / Mistake about space in email written in English in Log in form when entering email with space between symbols

### ISSUE THREAD

**Issue by SofyaKovalenko** [spellsofenglish/frontend#8]
**Environment**	
Windows 10, Google Chrome, version 109.0.5414.120, ASUS 1366 x 768

**Build version**	
v0.0.1

**Module**
Log in (FrontEnd)

**Severity**
Trivial

**Priority**
Low

**Description**
Mistake about space in email written in English in Log in form when entering email with space between symbols

**Steps to reproduce**
1. Open link https://spells.hedgi.ru/
2. Click "Log in"
3. Fill in field "Email" with space between letters in email like "qq w@bk.ru"

**Expected result**
1. Link is opened
2. Log in form is opened
3. Mistake "Your password must not contain spaces!" written in Russian (like other mistakes)
	
**Actual result**
1. Link is opened
2. Log in form is opened
3. Mistake "Your password must not contain spaces!" written in English

![bug ENG mistake ](https://user-images.githubusercontent.com/129843527/230144272-7a798330-eb93-4210-b657-8abe3b79a887.png)

**Comment by PavelPashyk** [comment]
Fixed bug №14

**Comment by SofyaKovalenko** [comment]
Re-test OK
